### ISSUE TITLE
The 'F2x==0.1.dev0' distribution was not found

### ISSUE THREAD

**Issue by melven** [DLR-SC/F2x#2]
After installing F2x on a SLED12 using our module system, I obtain the following error:

> F2x --help
> Traceback (most recent call last):
>   File "/tools/modulesystem/tools/F2x/F2x-git/install/sled12.x86_64.gcc-4.8.5.release/bin/F2x", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2912, in <module>
>     @_call_aside
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
>     f(_args, *_kwargs)
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 943, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 830, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'F2x==0.1.dev0' distribution was not found and is required by the application

There might just be some missing paths or so...any idea?

Here the output of the install script: [f2x_install_sled12.zip](https://github.com/DLR-SC/F2x/files/321919/f2x_install_sled12.zip)

**Comment by melven** [comment]
Ok my installer really just missed to set the PYTHONPATH correctly - usually this gets detected correctly...
